<?php

namespace Tests\Unit\Infrastructure;


use App\Domain\Coordinate;
use App\Domain\MovableInterface;
use App\Domain\TankOperationsMovableInterface;
use App\Infrastructure\InitScopeBasedIoCImplementation;
use App\Infrastructure\InversionOfControlContainer;
use App\Infrastructure\ScopeBasedResolveDependencyStrategy;
use PHPUnit\Framework\TestCase;

class InversionOfControlContainerTest extends TestCase
{
    public function testChangingScopes()
    {
        $container = new InversionOfControlContainer();
        InversionOfControlContainer::setInstance($container);
        $command = new InitScopeBasedIoCImplementation();
        $command->execute();

        $scope = clone ScopeBasedResolveDependencyStrategy::$root;

        $container->resolve("IoC.Register", 'scopeTest', function () {
            return 'test';
        })->execute();

        $this->assertSame('test', $container->resolve("scopeTest"));
        $container->resolve("Scopes.New", '1', $scope)->execute();
        $container->resolve("Scopes.Current.Set", '1')->execute();
        $container->resolve("IoC.Register", 'scopeTest', function () {
            return 'test2';
        })->execute();
        $this->assertSame('test2', $container->resolve("scopeTest"));
        $container->resolve("Scopes.Current.Set", 'default')->execute();
        $this->assertSame('test', $container->resolve("scopeTest"));
    }

    public function testAutoGenerating()
    {
        $container = new InversionOfControlContainer();
        InversionOfControlContainer::setInstance($container);
        $command = new InitScopeBasedIoCImplementation();
        $command->execute();

        $container->resolve(
            "IoC.Register",
            'TankOperationsMovableInterface.getPosition',
            function (array $arguments) {
                return $arguments[0]->getPosition();
            })->execute();

        $coordinate = new Coordinate(2, 2);

        $object = $this->createMock(MovableInterface::class);
        $object->expects(self::once())->method('getPosition')->willReturn($coordinate);

        $instanceOfAutogeneratedClass = $container->resolve(
            "Adapter",
            TankOperationsMovableInterface::class,
            $object
        );

        $result = $instanceOfAutogeneratedClass->getPosition();

        $this->assertEquals($coordinate, $result);
    }
}